kind: PersistentVolume
apiVersion: v1
metadata:
  name: ci-minio-pv
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce       
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /data/k8s
    server: 10.26.10.76 
