kind: PersistentVolume
apiVersion: v1
metadata:
  name: halyard-pv
  namespace: spinnaker
spec:
  accessModes:
    - ReadWriteOnce        #访问模式定义为只能以读写的方式挂载到单个节点
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: halyard-nfs
  nfs:
    path: /data/k8s/spinnaker/halyard
    server: 10.26.10.76 
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  namespace: spinnaker
spec:
  accessModes:
    - ReadWriteOnce        #访问模式定义为只能以读写的方式挂载到单个节点
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-nfs
  nfs:
    path: /data/k8s/spinnaker/redis
    server: 10.26.10.76
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  namespace: spinnaker
spec:
  accessModes:
    - ReadWriteOnce        #访问模式定义为只能以读写的方式挂载到单个节点
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-nfs
  nfs:
    path: /data/k8s/spinnaker/minio
    server: 10.26.10.76
